{% set version = "9.53.1" %}
{% set nopoint = "".join(version.split(".")) %}

package:
  name: ghostscript
  version: {{ version }}

source:
  url: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs{{ nopoint }}/ghostscript-{{ version }}.tar.gz
  sha512: 69f7bcca6c127d6d4bd5428b367c3810a3da75ae5ebd36982c62406867601b2d529d4ad188010b32cb4e1ad5b5b6655f9a57ba86e653b72a502203a4a0cd1d42
  patches:
    - dynlink_runtime.patch

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - gs --version

about:
  home: http://ghostscript.com/
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: An interpreter for the PostScript language and for PDF

extra:
  recipe-maintainers:
    - ocefpaf
    - leouieda
