{% set version = "9.53.3" %}
{% set nopoint = "".join(version.split(".")) %}

package:
  name: ghostscript
  version: {{ version }}

source:
  url: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs{{ nopoint }}/ghostscript-{{ version }}.tar.gz
  sha256: 96d04e4e464bddb062c1774ea895c4f1c1c94e6c4b62f5d32218ebd44dd65ba1
  patches:
    - dynlink_runtime.patch

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - gs --version

about:
  home: http://ghostscript.com/
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: An interpreter for the PostScript language and for PDF

extra:
  recipe-maintainers:
    - ocefpaf
    - leouieda
