travis:
  secure:
    BINSTAR_TOKEN: GGeEtLCitYTVa1WmkArEze+Q8ouzZ0YpLmVpiOe/C3Yn08+zah9NHq84n5DpxZGVdSaWxNON+rqkTiKKdHhvE8vMd+jmXuWOqsj3zNH3v9pab7kNc0+i6TSyZw8xDIuSa3S4GsbNJ3jclGEt+AOjaA4o8lybijJQJ6Km6IeUD45IXwg0O0NQ0hTDZI3J8DWVS+iugJrGAzBJUXQR25PoMURXFOy7giXBQIFX+nr6Tyr2x5kvuqhP6YT/9QcUMKs36NNhmeSkSbsU1hdv+/0f+xtKw3QXXIRuw2V1+KkhQiYZlMJRKFm9YFFm7AuAVG+r54s6VRC8UwuX+RCEFl2j4GdrEalRl4Yl3xi9PsNYZ9ZBA+VbqCqzzC2oAHL1pU8SvJzjKOosXV5Q6j7KDGDZDOzcbfA4so0Rd5DXnPQZW1anxVlIMUudy70Jb0GS+26I1kYHdL/vxt20FZAI7tm5mZ4aLVmz8eOx6f7HHq9rUYIffa6s0/RPLAVwtDkh8ec3rsNzFwlhU3lxDhUgnXlmYUjIAfmdZvvHcy0LV+KRbQvzZu+11+WULtuZPfXluU+rssYTTiDQM6Jpm3g06X1ugSVgW0dajfticyB5+9RnicKjqJiI9KIOOv7NsaqHImLEp2aEN05WwxE+gV5O1uDeuU8ehxn5TukmyE1a8Bk7xI8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
